## Import Pandas and Load the Excel Dataset

In this section, the Pandas library is imported and the `business.xlsx` Excel file is loaded into a DataFrame.

The `read_excel()` function is used to read data from the Excel file, and the data is stored in the variable `df` for further analysis and manipulation.

In [1]:
import pandas as pd
df= pd.read_excel("business.xlsx")

## Display the First Five Rows

The `head()` function is used to display the first five rows of the DataFrame.

It provides a quick overview of the dataset and helps us understand the structure and type of data stored in each column.

In [4]:
df.head()

,Footnotes,Unnamed: 1,Unnamed: 2
0,1,The Business Operations Survey samples busines...,BOS Series Data Collection ̶ DataInfo+
1,2,For more information about the number of busin...,New Zealand business demography
2,3,"See DataInfo+ for questionnaires, and more exp...",DataInfo+
3,4,Business size is defined by rolling mean emplo...,BOS Concepts ̶ DataInfo+
4,5,"Results for the mining and electricity, gas, w...",NaN

## Display Dataset Information

The `info()` function provides a concise summary of the DataFrame.

It displays the column names, number of non-null values, data types, and memory usage of the dataset. This helps us understand the structure and identify missing values.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Footnotes   18 non-null     object
 1   Unnamed: 1  15 non-null     str
 2   Unnamed: 2  4 non-null      str
dtypes: object(1), str(2)
memory usage: 612.0+ bytes

## Statistical Summary of the Dataset

The `describe()` function provides a statistical summary of the numerical columns in the DataFrame.

It displays values such as count, mean, standard deviation, minimum, maximum, and quartiles. This helps us understand the distribution and basic statistics of the numerical data.

In [6]:
df.describe()

,Footnotes,Unnamed: 1,Unnamed: 2
count,18,15,4
unique,18,15,4
top,1,The Business Operations Survey samples busines...,BOS Series Data Collection ̶ DataInfo+
freq,1,1,1

## Check the Shape of the Dataset

The `shape` attribute returns the dimensions of the DataFrame.

It shows the number of rows and columns in the form `(rows, columns)`.

In [8]:
df.shape

(20, 3)

## Selecting Specific Columns

In this section, specific columns are selected from the DataFrame.

The columns `Footnotes` and `Unnamed: 1` are selected using a list of column names. This allows us to work with only the required columns instead of the complete dataset.

In [9]:
df[["Footnotes", "Unnamed: 1"]]

,Footnotes,Unnamed: 1
0,1,The Business Operations Survey samples busines...
1,2,For more information about the number of busin...
2,3,"See DataInfo+ for questionnaires, and more exp..."
3,4,Business size is defined by rolling mean emplo...
4,5,"Results for the mining and electricity, gas, w..."
5,6,Counts of businesses are randomly rounded to b...
6,7,"Dollar values are rounded to nearest $1,000. A..."
7,8,Percentages are of total number of businesses ...
8,9,Percentages are of total number of businesses ...
9,10,Counts of employees are graduated randomly rou...
10,11,Results should be treated with caution due the...
11,12,Percentages are of total number of businesses ...
12,Symbols,NaN
13,.,Data not applicable or not data available
14,C,Confidentail
15,R,Revised
16,NaN,NaN
17,Note: The data collected refers to the most re...,NaN
18,NaN,NaN
19,Source: Stats NZ,NaN

## Selecting Rows and Columns Using loc

The `loc` method is used to select specific rows and columns from the DataFrame using their labels.

Here, rows from index `0` to `15` and the columns `Footnotes` and `Unnamed: 1` are selected.

In [11]:
df.loc[0:15, ["Footnotes", "Unnamed: 1"]]

   Footnotes                                         Unnamed: 1
0          1  The Business Operations Survey samples busines...
1          2  For more information about the number of busin...
2          3  See DataInfo+ for questionnaires, and more exp...
3          4  Business size is defined by rolling mean emplo...
4          5  Results for the mining and electricity, gas, w...
5          6  Counts of businesses are randomly rounded to b...
6          7  Dollar values are rounded to nearest $1,000. A...
7          8  Percentages are of total number of businesses ...
8          9  Percentages are of total number of businesses ...
9         10  Counts of employees are graduated randomly rou...
10        11  Results should be treated with caution due the...
11        12  Percentages are of total number of businesses ...
12   Symbols                                                NaN
13         .          Data not applicable or not data available
14         C                                       Confidentail
15         R                                            Revised

## Selecting Rows and Columns Using iloc

The `iloc` method is used to select rows and columns based on their integer positions.

Here, rows from index `0` to `7` and columns from position `1` to `2` are selected. The ending index is excluded.

In [13]:
df.iloc[0:8, 1:3]

,Unnamed: 1,Unnamed: 2
0,The Business Operations Survey samples busines...,BOS Series Data Collection ̶ DataInfo+
1,For more information about the number of busin...,New Zealand business demography
2,"See DataInfo+ for questionnaires, and more exp...",DataInfo+
3,Business size is defined by rolling mean emplo...,BOS Concepts ̶ DataInfo+
4,"Results for the mining and electricity, gas, w...",NaN
5,Counts of businesses are randomly rounded to b...,NaN
6,"Dollar values are rounded to nearest $1,000. A...",NaN
7,Percentages are of total number of businesses ...,NaN

## Check the Number of Rows

The `len()` function is used to find the total number of rows in the DataFrame.

It returns the number of records present in the dataset.

In [16]:
len(df)

20

## Selecting a Single Column

A single column can be selected from the DataFrame by using its column name inside square brackets.

Here, the `Footnotes` column is selected from the DataFrame.

In [22]:
df["Footnotes"]

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
Name: Footnotes, dtype: float64

## Converting Data to Numeric and Filtering Values

The `Footnotes` column is converted into numeric values using `pd.to_numeric()`.

The `errors="coerce"` parameter converts values that cannot be converted into numbers to `NaN`.

After conversion, the condition `df["Footnotes"] > 5` checks which values in the `Footnotes` column are greater than `5`.

The `print()` statement displays the resulting Boolean values (`True` or `False`).

In [21]:
df["Footnotes"]= pd.to_numeric(df["Footnotes"], errors="coerce")
print(df["Footnotes"]>5)

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Footnotes, dtype: bool

## Load the Student Dataset

In this section, the `student.csv` file is loaded into a Pandas DataFrame using the `read_csv()` function.

The dataset is stored in the variable `df`, which will be used for further data analysis and manipulation.

In [23]:
df=pd.read_csv("student.csv")

## Display the Dataset

The DataFrame `df` is displayed to view the complete dataset and inspect the available rows and columns.

In [24]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

## Filtering Rows Using Multiple Conditions

In this section, rows are filtered based on two conditions.

We select students whose `study_time_hours` is greater than 4 **and** whose `attendance_percent` is greater than 45.

The `&` operator is used to apply both conditions simultaneously.

In [28]:
df[(df["study_time_hours"]>4) & (df["attendance_percent"]>45 )]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
5,6,Female,4.2,78.2,5.7,High School,Yes,No,No,79.8,81.6,B
7,8,Male,6.2,86.4,6.0,High School,Yes,Yes,No,78.4,88.0,B
8,9,Male,5.3,81.3,6.7,Bachelors,Yes,No,No,63.8,84.4,B
...,...,...,...,...,...,...,...,...,...,...,...,...
991,992,Female,5.1,71.7,5.6,Bachelors,Yes,Yes,No,51.0,80.4,B
993,994,Female,6.2,87.6,5.9,PhD,Yes,No,No,75.4,92.7,A
994,995,Female,4.5,75.4,9.4,Bachelors,Yes,Yes,No,69.1,79.1,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B

## Creating a New Calculated Column

In this section, a new column named `Average Grade` is created by calculating the average of the `previous_grade` and `final_exam_score` columns.

The calculated value is stored in the new `Average Grade` column for each student.

In [29]:
df["Average Grade"]= (df["previous_grade"] + df["final_exam_score"])/2

## Display the Average Grade Column

The `Average Grade` column is displayed to view the calculated average grade of each student.

In [30]:
df["Average Grade"]

0      88.45
1      87.75
2      92.90
3      84.45
4      65.05
       ...
995    65.60
996    90.85
997    72.20
998    67.20
999    57.90
Name: Average Grade, Length: 1000, dtype: float64

## Display the Updated DataFrame

The complete DataFrame is displayed to view the dataset along with the newly created `Average Grade` column.

In [31]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,Average Grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A,88.45
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A,87.75
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A,92.90
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B,84.45
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D,65.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C,65.60
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A,90.85
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C,72.20
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B,67.20
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C,57.90

## GroupBy and Aggregation

In this section, the data is grouped based on the `part_time_job` column.

For each group, the average study time is calculated using `mean`, and the number of students in each group is calculated using `count`.

The result is stored in the `result` variable and then displayed using `print()`.

In [32]:
result = df.groupby("part_time_job")["study_time_hours"].agg(["mean", "count"])

print(result)

                   mean  count
part_time_job
No             3.589766    684
Yes            3.529430    316

## Creating a DataFrame

In this section, a new DataFrame named `df1` is created using a dictionary.

The DataFrame contains two columns: `student_id` and `name`, with three student records.

The `print()` function is used to display the created DataFrame.

In [34]:
df1 = pd.DataFrame({
    "student_id": [1, 2, 3],
    "name": ["James", "John", "Mary"]
})

print(df1)

   student_id   name
0           1  James
1           2   John
2           3   Mary

## Creating a Second DataFrame

In this section, a second DataFrame named `df2` is created using a dictionary.

The DataFrame contains two columns: `student_id` and `marks`. The `student_id` column will be used as the common column when merging `df1` and `df2`.

The `print()` function is used to display the created DataFrame.

In [36]:
df2 = pd.DataFrame({
    "student_id": [1, 2, 3],
    "marks": [85, 90, 78]
})
print(df2)

   student_id  marks
0           1     85
1           2     90
2           3     78

## Merging Two DataFrames

In this section, the two DataFrames `df1` and `df2` are merged using the common `student_id` column.

The `pd.merge()` function combines the information from both DataFrames based on the matching `student_id` values.

The merged DataFrame is stored in `result` and displayed using `print()`.

In [37]:
result = pd.merge(df1, df2, on="student_id")

print(result)

   student_id   name  marks
0           1  James     85
1           2   John     90
2           3   Mary     78

## Checking Row Counts After Merging

In this section, the number of rows in `df1`, `df2`, and the merged DataFrame `result` is checked.

The `len()` function is used to count the rows in each DataFrame. This helps verify the result of the merge and compare the number of records before and after merging.

In [38]:
print("df1 rows:", len(df1))
print("df2 rows:", len(df2))
print("Merged rows:", len(result))

df1 rows: 3
df2 rows: 3
Merged rows: 3